home/urls.py
from django.urls import path
from . import views
from django.conf.urls import handler404

app_name = 'home'

urlpatterns = [
    path('QuiSommesNous/', views.about, name='about'),
    path('', views.home, name='home'),
]


handler404 = "home.views.error_404"

project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from project import settings

urlpatterns = [
                  path('jcp_admin/', admin.site.urls),
                  path('', include('home.urls')),
                  path('nousServices/', include('services.urls')),
                  path('agenda/', include('reservation.urls')),
                  path('boutique/', include('produit.urls')),
                  path('contact/', include('contact.urls')),
                  path('', include('account.urls')),
                  path('connexion/', include('account.urls')),
                  path('monCompte/', include('user.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservation/urls.py
from django.urls import path
from . import views

app_name = 'reservation'

urlpatterns = [
    path('<str:pk>/', views.user_reservation, name='user_reservation'),
    path('nouvelleReservation/<str:pk>/', views.user_new_reservation, name='user_new_reservation'),
    path('MiseAjour/<str:pk>/', views.user_update_reservation, name='user_update_reservation'),
    path('Supprimer/<str:pk>/', views.user_delete_reservation, name='user_delete_reservation'),
]

reservation/models.py
from django.db import models
from django.contrib.auth.models import User


class Reservation(models.Model):
    fullName = models.CharField('Nom Complet', max_length=250, null=True)
    adress = models.CharField('Adresse', max_length=100, null=True)
    zip_code = models.IntegerField('Code Postal', null=True)
    city = models.CharField('Vile', max_length=100, null=True)
    email = models.EmailField('Email', max_length=250, null=True)
    phone = models.CharField('Telephone', max_length=20, null=False)
    date = models.CharField('Date', max_length=20, null=True, blank=True)
    hour = models.CharField('Heure', max_length=20, null=True, blank=True)
    message = models.TextField('Message', null=True)
    accepted = models.BooleanField('Valide', null=True)
    created_at = models.DateTimeField('Date Creation', auto_now_add=True, null=True)
    modified_at = models.DateTimeField('Date Mise Jour', auto_now=True, null=True)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.fullName

reservation/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Reservation


class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = [
            'fullName',
            'adress',
            'zip_code',
            'city',
            'email',
            'phone',
            'date',
            'hour',
            'message',
            'user',
        ]

reservation/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .forms import ReservationForm
from .models import Reservation


@login_required()
def user_reservation(request, pk):
    user = get_user_model().objects.get(id=pk)
    reservations = user.reservation_set.all()
    total_reservations = reservations.count()

    context = {
        'user_id': user,
        'reservations': reservations,
        'total_reservations': total_reservations
    }
    return render(request, 'reservation/reservations.html', context)


@login_required()
def user_new_reservation(request, pk):
    user = get_user_model().objects.get(id=pk)
    form = ReservationForm(initial={'user': user})

    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Votre réservation a bien été envoyé!')
            return redirect('reservation:user_reservation', pk=request.user.id)

    context = {'form': form}
    return render(request, 'reservation/new_reservation.html', context)


@login_required()
def user_update_reservation(request, pk):
    reservation_id = Reservation.objects.get(id=pk)
    form = ReservationForm(instance=reservation_id)

    if request.method == 'POST':
        form = ReservationForm(request.POST, instance=reservation_id)
        if form.is_valid():
            form.save()
            messages.success(request, 'Votre réservation a bien été modifé!')
            return redirect('reservation:user_reservation', pk=request.user.id)

    context = {'form': form}
    return render(request, 'reservation/new_reservation.html', context)


@login_required()
def user_delete_reservation(request, pk):
    reservation = Reservation.objects.get(id=pk)
    if request.method == 'POST':
        reservation.delete()
        messages.success(request, 'Votre réservation a bien été supprimé !')
        return redirect('reservation:user_reservation', pk=request.user.id)

    context = {'reservation': reservation}
    return render(request, 'reservation/delete_reservation.html', context)

reservation/templates/reservation/delete_reservation.html
{% extends 'main.html' %}
{% load widget_tweaks %}
{% load static %}

{% block styleshets %}
    <link rel="stylesheet" href="{% static 'css/reservation/reservation.css' %}">
{% endblock %}

{% block content %}
<section class="container py-5">
    <div class="container py-5 my-5">
        <div class="pb-3">
            <a href="{% url 'reservation:user_reservation' request.user.id %}" class="btn btn-outline-secondary">
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-arrow-back-up" width="32" height="32" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffbf00" fill="none" stroke-linecap="round" stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                    <path d="M9 13l-4 -4l4 -4m-4 4h11a4 4 0 0 1 0 8h-1" />
                </svg>
                retour réservations
            </a>
        </div>
        <h2 class="my-3">Détails de la réservation :</h2>
        <ul>
            <li>Nom : {{ reservation.fullName }}</li>
            <li>Date: {{ reservation.date }}</li>
            <li>Heure: {{ reservation.hour }}</li>
            <li>Adresse: {{ reservation.adress }}</li>
            <li>Code Postal: {{ reservation.zip_code }}</li>
            <li>Vile: {{ reservation.city }}</li>
            <li>Email: {{ reservation.email }}</li>
            <li>Téléphone: {{ reservation.phone }}</li>
            <li>Message: {{ reservation.message }}</li>
            <li>Rendez-vous acceptée ? :
                {% if reservation.accepted == True %}
                    OUI
                {% elif reservation.accepted == False %}
                    NON
                {% else %}
                    en attente..
                {% endif %}

            </li>
            <li>Crée le: {{ reservation.created_at|date }}</li>
        </ul>

        <div class="py-5">
            <form method="POST">
                {% csrf_token %}
                <!--DELETE CONFIRMATION TEXT-->
                <h1>Voulez-vous vraiment supprimer cette réservation?</h1>
                <p class="confirmation-message">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-alert-triangle" width="36" height="36" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffbf00" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                        <path d="M12 9v2m0 4v.01" />
                        <path d="M5 19h14a2 2 0 0 0 1.84 -2.75l-7.1 -12.25a2 2 0 0 0 -3.5 0l-7.1 12.25a2 2 0 0 0 1.75 2.75" />
                    </svg>
                    En validant la suppression cette action est permanente.
                </p>
                <!--BACK BUTTON-->
                <div class="pb-3">
                    <button type="submit" class="btn btn-outline-danger">
                    Supprimer
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-trash-x" width="32" height="32" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffbf00" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                        <path d="M4 7h16" />
                        <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" />
                        <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" />
                        <path d="M10 12l4 4m0 -4l-4 4" />
                    </svg>
                </button>
                    <a href="{% url 'reservation:user_reservation' request.user.id %}" class="btn btn-outline-secondary ms-3">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-arrow-back-up" width="32" height="32" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffbf00" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                            <path d="M9 13l-4 -4l4 -4m-4 4h11a4 4 0 0 1 0 8h-1" />
                        </svg>
                        retour réservations
                    </a>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

reservation/templates/reservation/new_reservation.html
{% extends 'main.html' %}
{% load widget_tweaks %}
{% load static %}

{% block styleshets %}
<link rel="stylesheet" href="{% static 'css/reservation/reservation.css' %}">
{% endblock %}

{% block content %}
<section class="py-5">
    <div class="container py-5 my-5">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <!--BACK BUTTON-->
                <div class="pb-3">
                    <a href="{% url 'reservation:user_reservation' request.user.id %}" class="btn btn-outline-secondary">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-arrow-back-up" width="32" height="32" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffbf00" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                            <path d="M9 13l-4 -4l4 -4m-4 4h11a4 4 0 0 1 0 8h-1" />
                        </svg>
                        retour réservations
                    </a>
                </div>
                <!--FORMULAIRE-->
                <form method="POST">
                    {% csrf_token %}
                    <!--FULL NAME-->
                    <div class="form-group mt-3">
                        {{ form.fullName.errors }}
                        {% render_field form.fullName class="form-control" placeholder="Nom complet*" type="text" %}
                    </div>
                    <!--ADRESS-->
                    <div class="form-group mt-3">
                        {{ form.adress.errors }}
                        {% render_field form.adress class="form-control" placeholder="Adresse*" type="text" %}
                    </div>
                    <!--CITY-->
                    <div class="form-group mt-3">
                        {{ form.city.errors }}
                        {% render_field form.city class="form-control" placeholder="Vile*" type="text" %}
                    </div>
                    <!--ZIP_CODE-->
                    <div class="form-group mt-3">
                        {{ form.zip_code.errors }}
                        {% render_field form.zip_code class="form-control" placeholder="Code postal*" type="text" %}
                    </div>
                    <!--EMAIL-->
                    <div class="form-group mt-3">
                        {{ form.email.errors }}
                        {% render_field form.email class="form-control" placeholder="Email*" type="email" %}
                    </div>
                    <!--PHONE-->
                    <div class="form-group mt-3">
                        {{ form.phone.errors }}
                        {% render_field form.phone class="form-control" placeholder="Votre téléphone*" type="phone" %}
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <!--DATE-->
                            <div class="form-group mt-3">
                                {{ form.date.errors }}
                                {% render_field form.date class="form-control" placeholder="Date*" type="date" %}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <!--HOUR-->
                            <div class="form-group mt-3">
                                {{ form.hour.errors }}
                                {% render_field form.hour class="form-control" placeholder="Heure*" type="time" %}
                            </div>
                        </div>
                    </div>
                    <!--MESSAGE-->
                    <div class="form-group mt-3">
                        {{ form.message.errors }}
                        {% render_field form.message class="form-control" placeholder="Votre message*" type="text" %}
                    </div>
                    <!--MESSAGE-->
                    <div class="form-group mt-3 no-display">
                        {{ form.user.errors }}
                        {% render_field form.user class="form-control" placeholder="user" type="hidden" %}
                    </div>

                    <!--BUTTON SUBMIT-->
                    <div class="form-group mt-3">
                        <button type="submit" class="btn btn-outline-success">
                            Envoyer
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-plus" width="32" height="32" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffbf00" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                <line x1="12" y1="5" x2="12" y2="19" />
                                <line x1="5" y1="12" x2="19" y2="12" />
                            </svg>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

reservation/templates/reservation/reservations.html
{% extends 'main.html' %}
{% load static %}

{% block styleshets %}
<link rel="stylesheet" href="{% static 'css/reservation/reservation.css' %}">
{% endblock %}

{% block content %}
<h1 class="pt-5 mt-5 ps-3">
    Mes réservations
    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-clipboard-list" width="42" height="42" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffbf00" fill="none" stroke-linecap="round" stroke-linejoin="round">
        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
        <path d="M9 5h-2a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-12a2 2 0 0 0 -2 -2h-2" />
        <rect x="9" y="3" width="6" height="4" rx="2" />
        <line x1="9" y1="12" x2="9.01" y2="12" />
        <line x1="13" y1="12" x2="15" y2="12" />
        <line x1="9" y1="16" x2="9.01" y2="16" />
        <line x1="13" y1="16" x2="15" y2="16" />
    </svg>
</h1>


<div class="container-fluid py-5 reservation-box">
    <div>
        <p>Nombre total de réservations: <span><i><b>{{ total_reservations }}</b></i></span></p>
    </div>
    <div>
    <!--MESSAGES SUCCESS/ERROR-->
    {% for message in messages %}
        {% if message.tags == 'success' %}
        <div class="alert alert-success alert-dismissible d-flex justify-content-center" role="alert">
            <div>
                <img src="{% static 'images/logo.png' %}" alt="logo entreprise"
                style="width:60px;border-radius: 50%;">
            </div>
            <div>
                <a href="{% url 'reservation:user_reservation' request.user.id %}" class="close" data-dismiss="alert"
                aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
            {% elif message.tags == 'error' %}
            </div>
                <div class="alert alert-success alert-dismissible d-flex justify-content-center" role="alert">
            <div>
                <img src="{% static 'images/logo.png' %}" alt="logo entreprise"
                style="width:60px;border-radius: 50%;">
            </div>
            <div>
                <a href="{% url 'reservation:user_reservation' %}" class="close" data-dismiss="alert"
                aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        </div>
        {% endif %}
    {% endfor %}
    </div>
    <div class="responsive-table">
        <!--TABLE-->
        <table class="table table-striped table-warning">
            <thead>
            <tr>
                <th scope="col">Nom</th>
                <th scope="col">Adresse</th>
                <th scope="col">Code Postal</th>
                <th scope="col">Vile</th>
                <th scope="col">Date</th>
                <th scope="col">Heure</th>
                <th scope="col">Message</th>
                <th scope="col">Validé ?</th>
    <!--            <th scope="col">user_id</th>-->
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            <!--SHOW TABLE IF FOUND RESERVATIONS-->
            {% if total_reservations > 0 %}
                {% for reservation in reservations %}
                    <tr>
                        <td data-label="Nom:" scope="row">{{ reservation.fullName }}</td>
                        <td data-label="Adresse:" scope="row">{{ reservation.adress }}</td>
                        <td data-label="Code Postal:" scope="row">{{ reservation.zip_code }}</td>
                        <td data-label="Vile:" scope="row">{{ reservation.city }}</td>
                        <td data-label="Date:" scope="row">{{ reservation.date }}</td>
                        <td data-label="Heure:" scope="row">{{ reservation.hour }}</td>
                        <td data-label="Message:" scope="row">{{ reservation.message }}</td>
                        <td data-label="Validé ?:" scope="row">
                            {% if reservation.accepted %}
                                Oui
                            {% else %}
                                Non
                            {% endif %}
                        </td>
    <!--                    <td scope="row">{{ reservation.user_id }}</td>-->
                        <td scope="row">
                            <a href="{% url 'reservation:user_update_reservation' reservation.id %}" class="btn btn-outline-primary">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-edit" width="26" height="26" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffbf00" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                    <path d="M9 7h-3a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-3" />
                                    <path d="M9 15h3l8.5 -8.5a1.5 1.5 0 0 0 -3 -3l-8.5 8.5v3" />
                                    <line x1="16" y1="5" x2="19" y2="8" />
                                </svg>
                            </a>
                            <a href="{% url 'reservation:user_delete_reservation' reservation.id %}" class="btn btn-outline-danger">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-trash" width="26" height="26" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffbf00" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                    <line x1="4" y1="7" x2="20" y2="7" />
                                    <line x1="10" y1="11" x2="10" y2="17" />
                                    <line x1="14" y1="11" x2="14" y2="17" />
                                    <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" />
                                    <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" />
                                </svg>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            <!--SHOW TEXT 'NOT FOUND RESERVATIONS'-->
                {% else %}
                    <tr>
                        <td colspan="10">
                            <i>
                                Vous n'avez actuellement aucune reservation.
                                <br>
                                Vous pouvez prendre un rendez-vous en cliquant sur le bouton 'Nouvelle réservation' !
                            </i>
                        </td>
                    </tr>
            {% endif %}
            </tbody>
        </table>
    </div>

<!--NEW RESERVATION BUTTON-->
    <div>
        <a href="{% url 'reservation:user_new_reservation' request.user.id %}" class="btn btn-outline-success">
            Nouvelle réservation
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-plus" width="36" height="36" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffbf00" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                <line x1="12" y1="5" x2="12" y2="19" />
                <line x1="5" y1="12" x2="19" y2="12" />
            </svg>
        </a>
    </div>
</div>

{% endblock %}