account/urls.py
from django.urls import path
from . import views

app_name = 'my_account'

urlpatterns = [
    path('deconnexion/', views.logout_user, name='logout'),
    path('rgpd/', views.rgpd, name='rgpd'),
    path('connexion/', views.connexion, name='connexion'),
    path('inscription/', views.inscription, name='inscription'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('changer_password/', views.password_change, name='password_change'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('reset/<uidb64>/<token>', views.password_reset_confirm, name='password_reset_confirm'),
]

home/urls.py
from django.urls import path
from . import views
from django.conf.urls import handler404

app_name = 'home'

urlpatterns = [
    path('QuiSommesNous/', views.about, name='about'),
    path('', views.home, name='home'),
]


handler404 = "home.views.error_404"

project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from project import settings

urlpatterns = [
                  path('jcp_admin/', admin.site.urls),
                  path('', include('home.urls')),
                  path('nousServices/', include('services.urls')),
                  path('agenda/', include('reservation.urls')),
                  path('boutique/', include('produit.urls')),
                  path('contact/', include('contact.urls')),
                  path('', include('account.urls')),
                  path('connexion/', include('account.urls')),
                  path('monCompte/', include('user.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservation/urls.py
from django.urls import path
from . import views

app_name = 'reservation'

urlpatterns = [
    path('<str:pk>/', views.user_reservation, name='user_reservation'),
    path('nouvelleReservation/<str:pk>/', views.user_new_reservation, name='user_new_reservation'),
    path('MiseAjour/<str:pk>/', views.user_update_reservation, name='user_update_reservation'),
    path('Supprimer/<str:pk>/', views.user_delete_reservation, name='user_delete_reservation'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('profil/<username>', views.user_home, name='user_home'),
    path('MettreAjour/<username>', views.user_update_profil, name='update_profil'),
    path('SupprimerCompte/<username>', views.user_delete_profil, name='delete_profil'),
]

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django.contrib.auth import get_user_model
from django import forms


class UserUpdateProfile(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'email']

user/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.shortcuts import render, redirect
# from user.forms import Update_profile
from user.forms import UserUpdateProfile
from django.contrib.auth import get_user_model


@login_required(login_url='user:user_home')
def user_home(request, username):
    user = get_user_model().objects.get(username=username)
    reservations = user.reservation_set.all()
    total_reservations = reservations.count()

    context = {
        'total_reservations': total_reservations,
        'reservations': reservations
    }
    return render(request, 'user/user_home.html', context)


@login_required()
def user_update_profil(request, username):
    if request.method == 'POST':
        user = request.user
        form = UserUpdateProfile(request.POST, instance=user)
        if form.is_valid():
            user_form = form.save()
            messages.success(request, f"{user_form.username} Votre compte a bien été mis à jour!")
            return redirect('user:user_home', user_form.username)
        else:
            for error in list(form.errors.values()):
                messages.error(request, error)

    user = get_user_model().objects.filter(username=username).first()
    if user:
        form = UserUpdateProfile(instance=user)
        return render(request, 'user/update_profil.html', context={'form': form})
    return redirect('user:user_home', request.user.username)


@login_required(login_url='user:delete_profil')
def user_delete_profil(request, username=None):
    user = get_user_model().objects.filter(username=username).first()
    if request.method == 'POST':
        user.delete()
        messages.success(request, 'Votre compte a bien été supprimé !')
        return redirect('home:home')
    context = {'user': user}
    return render(request, 'user/delete_profil.html', context)

user/templates/user/delete_profil.html
{% extends 'main.html' %}
{% load widget_tweaks %}
{% load static %}

{% block styleshets %}
<link rel="stylesheet" href="{% static 'css/reservation/reservation.css' %}">
{% endblock %}

{% block content %}
<section class="container py-5">
    <div class="container py-5 my-5">
        <div class="py-5">
            <form method="POST">
                {% csrf_token %}

                <!--CONFIRMATION TEXT-->
                <h1>Voulez-vous vraiment supprimer votre compte ?</h1>
                <p class="confirmation-message">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-alert-triangle" width="36" height="36" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffbf00" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                        <path d="M12 9v2m0 4v.01" />
                        <path d="M5 19h14a2 2 0 0 0 1.84 -2.75l-7.1 -12.25a2 2 0 0 0 -3.5 0l-7.1 12.25a2 2 0 0 0 1.75 2.75" />
                    </svg>
                    En validant la suppression cette action est permanente.
                </p>

                <div class="pb-3">
                    <!--DELETE BUTTON-->
                    <button type="submit" class="btn btn-outline-danger">
                        Supprimer
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-trash-x" width="32" height="32" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffbf00" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                            <path d="M4 7h16" />
                            <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" />
                            <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" />
                            <path d="M10 12l4 4m0 -4l-4 4" />
                        </svg>
                    </button>
                    <!--BACK BUTTON-->
                    <a href="{% url 'user:user_home' request.user.username %}" class="btn btn-outline-secondary ms-3">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-arrow-back-up" width="32" height="32" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffbf00" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                            <path d="M9 13l-4 -4l4 -4m-4 4h11a4 4 0 0 1 0 8h-1" />
                        </svg>
                        retour réservations
                    </a>
                </div>
            </form>
        </div>
    </div>
</section>



{% endblock %}

user/templates/user/update_profil.html
{% extends 'main.html' %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% load static %}

{% block styleshets %}
<link rel="stylesheet" href="{% static 'css/contact/contact.css' %}">
{% endblock %}

{% block content %}
<section class="container text-center pt-5 mt-5">
    <h1 class="mt-5 animate__animated  animate__slideInRight">Mettre à jour mes informations</h1>
    <div class="mx-auto py-5 col-md-6 col-sm-8 animate__animated  animate__slideInLeft">
        <!--BACK BUTTON-->
        <div class="pb-3 text-start">
            <a href="{% url 'user:user_home' request.user.username %}" class="btn btn-outline-secondary">
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-arrow-back-up" width="32"
                     height="32" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffbf00" fill="none"
                     stroke-linecap="round" stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                    <path d="M9 13l-4 -4l4 -4m-4 4h11a4 4 0 0 1 0 8h-1"/>
                </svg>
                retour profil
            </a>
        </div>
        <!--MESSAGES SUCCESS/ERROR-->
        {% for message in messages %}
        {% if message.tags == 'success' %}
        <div class="alert alert-success alert-dismissible d-flex justify-content-center" role="alert">
            <div>
                <img src="{% static 'images/logo.png' %}" alt="logo entreprise"
                     style="width:60px;border-radius: 50%;">
            </div>
            <div>
                <a href="{% url 'user:update_profil' request.user.id %}" class="close" data-dismiss="alert"
                   aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        </div>
        {% elif message.tags == 'error' %}
        <div class="alert alert-danger alert-dismissible d-flex justify-content-center" role="alert">
            <div>
                <img src="{% static 'images/logo.png' %}" alt="logo entreprise"
                     style="width:60px;border-radius: 50%;">
            </div>
            <div>
                <a href="{% url 'user:update_profil' request.user.id %}" class="close" data-dismiss="alert"
                   aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        </div>
        {% endif %}
        {% endfor %}
        <!--FORMULAIRE-->
        <form method="POST">
            {% csrf_token %}
            <div class="text-start">
                <div class="form-group mt-3">
                    <label>Nom complet</label>
                    {{ form.first_name.errors }}
                    {% render_field form.first_name class="form-control" placeholder="Nom complet" type="text" %}
                </div>
                <div class="form-group mt-3">
                    <label>Email</label>
                    {{ form.email.errors }}
                    {% render_field form.email class="form-control" placeholder="Nom complet" type="email" %}
                </div>
                <div class="form-group mt-3">
                </div>
                <div>
                    <a href="{% url 'my_account:password_change' %}">Changer Mot de passe?</a>
                </div>
            </div>
            <!--button-->
            <button type="submit" value="Submit" class="btn btn-warning mt-3 w-100">Mettre à jour</button>
        </form>
    </div>
</section>
{% endblock %}

user/templates/user/user_home.html
{% extends 'main.html' %}
{% load static %}

{% block styleshets %}
<link rel="stylesheet" href="{% static 'css/user/home.css' %}">
{% endblock %}

{% block content %}
<h1 class="ms-3 mt-5 pt-5">Bienvenue <b><i>{{ request.user.username }}</i></b></h1>
<section class="user_profile py-5 my-5">
    <div class="container">
        <div class="row my-5">
            <div class="box col-lg-4 col-md-12">
                <!--PROFILE INFORMATIONS-->
                <div class="p-3">
                    <div class="row py-2">
                        <div class="col-md-12">
                            <p>
                            <h2>Mes informations de Profil</h2></p>
                        </div>
                        <!--UPDATE PROFILE BUTTON-->
                        <div class="col-md-12">
                            <p>
                            <h3>
                                <a href="{% url 'user:update_profil' request.user.username %}"
                                   class="btn btn-outline-secondary" style="font-size:16px;">
                                    <svg xmlns="http://www.w3.org/2000/svg"
                                         class="icon icon-tabler icon-tabler-settings"
                                         width="22" height="22" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffbf00"
                                         fill="none" stroke-linecap="round" stroke-linejoin="round">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                        <path d="M10.325 4.317c.426 -1.756 2.924 -1.756 3.35 0a1.724 1.724 0 0 0 2.573 1.066c1.543 -.94 3.31 .826 2.37 2.37a1.724 1.724 0 0 0 1.065 2.572c1.756 .426 1.756 2.924 0 3.35a1.724 1.724 0 0 0 -1.066 2.573c.94 1.543 -.826 3.31 -2.37 2.37a1.724 1.724 0 0 0 -2.572 1.065c-.426 1.756 -2.924 1.756 -3.35 0a1.724 1.724 0 0 0 -2.573 -1.066c-1.543 .94 -3.31 -.826 -2.37 -2.37a1.724 1.724 0 0 0 -1.065 -2.572c-1.756 -.426 -1.756 -2.924 0 -3.35a1.724 1.724 0 0 0 1.066 -2.573c-.94 -1.543 .826 -3.31 2.37 -2.37c1 .608 2.296 .07 2.572 -1.065z"/>
                                        <circle cx="12" cy="12" r="3"/>
                                    </svg>
                                    Editer
                                </a>
                            </h3>
                            </p>
                        </div>
                        <!--MESSAGES SUCCESS/ERROR-->
                        <div>
                            {% for message in messages %}
                            {% if message.tags == 'success' %}
                            <div class="alert alert-success alert-dismissible d-flex justify-content-center"
                                 role="alert">
                                <div>
                                    <img src="{% static 'images/logo.png' %}" alt="logo entreprise"
                                         style="width:60px;border-radius: 50%;">
                                </div>
                                <div>
                                    <a href="{% url 'user:update_profil' request.user.id %}" class="close"
                                       data-dismiss="alert"
                                       aria-label="close">&times;</a>
                                    {{ message|safe|escape }}
                                </div>
                            </div>
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    <!--username-->
                    <div>
                        <p class="mb-0">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user" width="30"
                                 height="30" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffbf00" fill="none"
                                 stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                <circle cx="12" cy="7" r="4"/>
                                <path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2"/>
                            </svg>
                            <b>Nom d'utilisateur</b></p>
                        <p class="ms-5">{{ request.user.username }}</p>
                    </div>
                    <!--full_name-->
                    <div>
                        <p class="mb-0">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-signature"
                                 width="30" height="30" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffbf00"
                                 fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                <path d="M3 17c3.333 -3.333 5 -6 5 -8c0 -3 -1 -3 -2 -3s-2.032 1.085 -2 3c.034 2.048 1.658 4.877 2.5 6c1.5 2 2.5 2.5 3.5 1l2 -3c.333 2.667 1.333 4 3 4c.53 0 2.639 -2 3 -2c.517 0 1.517 .667 3 2"/>
                            </svg>
                            <b>Nom complet</b>
                        </p>
                        <p class="ms-5">{{ request.user.first_name }}</p>
                    </div>
                    <!--email-->
                    <div>
                        <p class="mb-0">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-at" width="30"
                                 height="30" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffbf00" fill="none"
                                 stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                <circle cx="12" cy="12" r="4"/>
                                <path d="M16 12v1.5a2.5 2.5 0 0 0 5 0v-1.5a9 9 0 1 0 -5.5 8.28"/>
                            </svg>
                            <b>Email</b>
                        </p>
                        <p class="ms-5">{{ request.user.email }}</p>
                    </div>
                    <!--password-->
                    <div>
                        <p class="mb-0">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-lock" width="30"
                                 height="30" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffbf00" fill="none"
                                 stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                <rect x="5" y="11" width="14" height="10" rx="2"/>
                                <circle cx="12" cy="16" r="1"/>
                                <path d="M8 11v-4a4 4 0 0 1 8 0v4"/>
                            </svg>
                            <b>Mot de passe</b>
                        </p>
                        <p class="ms-5">********</p>
                    </div>
                </div>
                <!--DELETE ACCOUNT-->
                <div>
                    <p>
                        <a href="{% url 'user:delete_profil' request.user.username %}" class="btn btn-outline-danger">
                            <small>Supprimer mon compte</small>
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-trash"
                                 width="28" height="28" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffbf00"
                                 fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                <line x1="4" y1="7" x2="20" y2="7"/>
                                <line x1="10" y1="11" x2="10" y2="17"/>
                                <line x1="14" y1="11" x2="14" y2="17"/>
                                <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12"/>
                                <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3"/>
                            </svg>
                        </a>
                    </p>
                </div>
            </div>
            <!--LITLE SECTION FOR RESERVATIONS-->
            <div class="box box-reservations col-lg-8 col-md-12">
                <!--PROFILE INFORMATIONS-->
                <div class="p-3">
                    <div class="row py-2">
                        <div class="col-md-8">
                            <p>
                            <h2>Mes réservations</h2></p>
                        </div>
                        <!--UPDATE PROFILE BUTTON-->
                        <div class="col-md-4">
                            <p>
                            <h3>
                                <a href="{% url 'reservation:user_reservation' request.user.id %}"
                                   class="btn btn-outline-secondary" style="font-size:16px;">
                                    <svg xmlns="http://www.w3.org/2000/svg"
                                         class="icon icon-tabler icon-tabler-settings"
                                         width="22" height="22" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffbf00"
                                         fill="none" stroke-linecap="round" stroke-linejoin="round">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                        <path d="M10.325 4.317c.426 -1.756 2.924 -1.756 3.35 0a1.724 1.724 0 0 0 2.573 1.066c1.543 -.94 3.31 .826 2.37 2.37a1.724 1.724 0 0 0 1.065 2.572c1.756 .426 1.756 2.924 0 3.35a1.724 1.724 0 0 0 -1.066 2.573c.94 1.543 -.826 3.31 -2.37 2.37a1.724 1.724 0 0 0 -2.572 1.065c-.426 1.756 -2.924 1.756 -3.35 0a1.724 1.724 0 0 0 -2.573 -1.066c-1.543 .94 -3.31 -.826 -2.37 -2.37a1.724 1.724 0 0 0 -1.065 -2.572c-1.756 -.426 -1.756 -2.924 0 -3.35a1.724 1.724 0 0 0 1.066 -2.573c-.94 -1.543 .826 -3.31 2.37 -2.37c1 .608 2.296 .07 2.572 -1.065z"/>
                                        <circle cx="12" cy="12" r="3"/>
                                    </svg>
                                    Voir réservations
                                </a>
                            </h3>
                            </p>
                        </div>
                    </div>
                    <!--                    -->
                    <!--TABLE-->
                    <div class="table-responsive-md">
                        <table class="table table-striped table-warning">
                            <thead>
                            <tr>
                                <th scope="col">Nom</th>
                                <th scope="col">Code Postal</th>
                                <th scope="col">Date</th>
                                <th scope="col">Heure</th>
                                <th scope="col">Validé ?</th>
                            </tr>
                            </thead>
                            <tbody>
                            <!--SHOW TABLE IF FOUND RESERVATIONS-->
                            {% if total_reservations > 0 %}
                            {% for reservation in reservations %}
                            <tr>
                                <td scope="row">{{ reservation.fullName }}</td>
                                <td scope="row">{{ reservation.zip_code }}</td>
                                <td scope="row">{{ reservation.date }}</td>
                                <td scope="row">{{ reservation.hour }}</td>
                                <td scope="row">
                                    {% if reservation.accepted %}
                                    Oui
                                    {% else %}
                                    Non
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                            <!--SHOW TEXT 'NOT FOUND RESERVATIONS'-->
                            {% else %}
                            <tr>
                                <td colspan="10">Aucune reservation trouvé !</td>
                            </tr>
                            {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}