account/urls.py
from django.urls import path
from . import views

app_name = 'my_account'

urlpatterns = [
    path('deconnexion/', views.logout_user, name='logout'),
    path('rgpd/', views.rgpd, name='rgpd'),
    path('connexion/', views.connexion, name='connexion'),
    path('inscription/', views.inscription, name='inscription'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('changer_password/', views.password_change, name='password_change'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('reset/<uidb64>/<token>', views.password_reset_confirm, name='password_reset_confirm'),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.contact, name='contact')
]

home/urls.py
from django.urls import path
from . import views
from django.conf.urls import handler404

app_name = 'home'

urlpatterns = [
    path('QuiSommesNous/', views.about, name='about'),
    path('', views.home, name='home'),
]


handler404 = "home.views.error_404"

produit/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.boutique, name='boutique'),
]

project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from project import settings

urlpatterns = [
                  path('jcp_admin/', admin.site.urls),
                  path('', include('home.urls')),
                  path('nousServices/', include('services.urls')),
                  path('agenda/', include('reservation.urls')),
                  path('boutique/', include('produit.urls')),
                  path('contact/', include('contact.urls')),
                  path('', include('account.urls')),
                  path('connexion/', include('account.urls')),
                  path('monCompte/', include('user.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('profil/<username>', views.user_home, name='user_home'),
    path('MettreAjour/<username>', views.user_update_profil, name='update_profil'),
    path('SupprimerCompte/<username>', views.user_delete_profil, name='delete_profil'),
]

templates/bases/alert_info.html
<div class="container info_alert_message">
    <div class="alert alert-info alert-dismissible py-5">
        <div>
            <span id="close_alert_message">&times;</span>
            <h2>*** Nouveau ***</h2>
            <h5>
                Nous vous proposons des nouvelles fonctionnalités sur la
                nouvelle application web!
            </h5>
            <p>
                Vous pouvez désormais accéder à votre compte en ligne et
                réserver des créneaux directement sur votre espace client.
            </p>
            <h3>Ne perdez pas de temps, inscrivez-vous !!!</h3>
        </div>
    </div>
</div>

templates/bases/footer.html
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'css/bases/footer.css' %}">
{% endblock %}
<div class="footer-section">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4 d-flex flex-column">
                <ul class="d-inline-flex mx-auto">
                    <li class="p-3"><a href="https://m.facebook.com/profile.php?id=100069893835804" target="_blank"><img src="{% static 'icons/facebook.png' %}" alt="logo facebook"></a></li>
<!--                    <li class="p-3"><a href=""><img src="{% static 'icons/instagram.png' %}" alt="logo instagram"></a></li>-->
                    <li class="p-3"><a href="https://www.linkedin.com/in/jo%C3%A3o-cerqueira-pereira-lda-b064b443/?originalSubdomain=pt" target="_blank"><img src="{% static 'icons/linkedin.png' %}"  alt="logo linkedIn"></a></li>
                </ul>
                <ul class="links d-inline-flex mx-auto">
                    <li class="p-3"><a href="{% url 'home:home' %}">Accueil</a></li>
                    <li class="p-3"><a href="{% url 'home:about' %}">A Propos</a></li>
                </ul>
                <ul class="d-inline-flex mx-auto">
<!--                    <li class="p-3"><a href="">Agenda</a></li>-->
<!--                    <li class="p-3"><a href="{% url 'product:boutique' %}">Notre Boutique</a></li>-->
                    <li class="p-3"><a href="{% url 'services:services' %}">Nous Services</a></li>
                    <li class="p-3"><a href="{% url 'contact:contact' %}">Contact</a></li>
                    <li class="p-3"><small><i><a href="{% url 'my_account:rgpd' %}" target="_blank">Consulter RGPD</a></i></small></li>
                </ul>
            </div>
            <div class="coords col-md-4 d-flex flex-column text-center mt-3">
                <p>Une Urgence?<img src="{% static 'icons/urgence.png' %}" alt="Icône ilustration alerte."></p>
                <p>+351 258 452 335</p>
                <p>geral@joaocerqueirapereira.com</p>
                <p>joaocpereiralda@gmail.com</p>
            </div>
            <div class="col-md-4 text-center">
                <div>
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2974.235871038348!2d-8.417875784302149!3d41.80167897817175!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd2508e014be3447%3A0xb4fdc9bcc20baebf!2sJo%C3%A3o%20Cerqueira%20Pereira%20Lda!5e0!3m2!1sfr!2sfr!4v1664143832111!5m2!1sfr!2sfr" width="300" height="200" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
            </div>
        </div>
    </div>
    <div class="copyrigth text-center">
        <p class="m-0">&copy;João Cerqueira pereira, Lda - Licence nº 51414. 2022. Tous droits réservés.</p>
        <p class="m-0"><i>Site développé par : <a href="https://nunofernandes-dev.com" target="_blank">nunofernandes-dev.com</a></i></p>
    </div>
</div>

templates/bases/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:home' %}"><img src="{% static 'images/logo.png' %}" alt="logo entreprise"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto me-2 mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'home:home' %}">Accueil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:about' %}">A propos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'services:services' %}">Nos Services</a>
                </li>
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="{% url 'product:boutique' %}">Notre Boutique</a>-->
<!--                </li>-->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contact:contact' %}">Contact</a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown me-5 mx-3">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-settings" width="22" height="22" viewBox="0 0 24 24" stroke-width="1.5" stroke="#8A7900" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                            <path d="M10.325 4.317c.426 -1.756 2.924 -1.756 3.35 0a1.724 1.724 0 0 0 2.573 1.066c1.543 -.94 3.31 .826 2.37 2.37a1.724 1.724 0 0 0 1.065 2.572c1.756 .426 1.756 2.924 0 3.35a1.724 1.724 0 0 0 -1.066 2.573c.94 1.543 -.826 3.31 -2.37 2.37a1.724 1.724 0 0 0 -2.572 1.065c-.426 1.756 -2.924 1.756 -3.35 0a1.724 1.724 0 0 0 -2.573 -1.066c-1.543 .94 -3.31 -.826 -2.37 -2.37a1.724 1.724 0 0 0 -1.065 -2.572c-1.756 -.426 -1.756 -2.924 0 -3.35a1.724 1.724 0 0 0 1.066 -2.573c-.94 -1.543 .826 -3.31 2.37 -2.37c1 .608 2.296 .07 2.572 -1.065z" />
                            <circle cx="12" cy="12" r="3" />
                        </svg>
                        Actions
                    </a>
                    <!--dropdown actions-->
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                        <li>
                            <a class="dropdown-item" href="{% url 'user:user_home' request.user.username %}">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user" width="22" height="22" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffbf00" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                    <circle cx="12" cy="7" r="4" />
                                    <path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2" />
                                </svg>
                                Mon profil
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'reservation:user_reservation' request.user.id %}">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-calendar-event" width="22" height="22" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffbf00" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                    <rect x="4" y="5" width="16" height="16" rx="2" />
                                    <line x1="16" y1="3" x2="16" y2="7" />
                                    <line x1="8" y1="3" x2="8" y2="7" />
                                    <line x1="4" y1="11" x2="20" y2="11" />
                                    <rect x="8" y="15" width="2" height="2" />
                                </svg>
                                Mes reservations
                            </a>
                        </li>
                        <li><hr class="dropdown-divider"></li>
                        <li>
                            <a class="dropdown-item" href="{% url 'my_account:logout' %}">
                            me déconnecter
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-logout" width="22" height="22" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffbf00" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                <path d="M14 8v-2a2 2 0 0 0 -2 -2h-7a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h7a2 2 0 0 0 2 -2v-2"/>
                                <path d="M7 12h14l-3 -3m0 6l3 -3"/>
                            </svg>
                            </a>
                        </li>
                    </ul>
                </li>
                <!--logout-->
                <li class="nav-item px-2">
                    <a href="{% url 'my_account:logout' %}" class="nav-link p-1" title="Me déconnecter du compte.">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-logout" width="32"
                             height="32" viewBox="0 0 24 24" stroke-width="1.5" stroke="#8A7900" fill="none"
                             stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                            <path d="M14 8v-2a2 2 0 0 0 -2 -2h-7a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h7a2 2 0 0 0 2 -2v-2"/>
                            <path d="M7 12h14l-3 -3m0 6l3 -3"/>
                        </svg>
                    </a>
                </li>
                {% else %}
                <!--connexion/inscription/logout-->
                <ul class="connection-icons d-flex">
                    <!--connection-->
                    <li class="px-2">
                        <a href="{% url 'my_account:connexion' %}" class="p-1" title="Connexion au compte utilisateur.">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user-check"
                                 width="32" height="32" viewBox="0 0 24 24" stroke-width="1.5" stroke="#8A7900" fill="none"
                                 stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                <circle cx="9" cy="7" r="4"/>
                                <path d="M3 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2"/>
                                <path d="M16 11l2 2l4 -4"/>
                            </svg>
                        </a>
                    </li>
                    <!--inscription-->
                    <li class="px-2">
                        <a href="{% url 'my_account:inscription' %}" class="p-1" title="Créer un compte utilisateur.">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user-plus"
                                 width="32" height="32" viewBox="0 0 24 24" stroke-width="1.5" stroke="#8A7900" fill="none"
                                 stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                <circle cx="9" cy="7" r="4"/>
                                <path d="M3 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2"/>
                                <path d="M16 11h6m-3 -3v6"/>
                            </svg>
                        </a>
                    </li>
                </ul>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block scripts %}
    <!--bootstrap5 js cdn-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
{% endblock %}